### ISSUE TITLE
1.3.4 crash en cliquant sur volume master d'un looper

### ISSUE THREAD

**Issue by Ezrabox** [OrganicOrchestra/LGML#11]
0   LGML                                0x003fe515 _ZN4juceL11handleCrashEi + 69
1   libsystem_platform.dylib            0xa1742e5b _sigtramp + 43
2   ???                                 0xffffffff 0x0 + 4294967295
3   LGML                                0x00191650 _ZN15OSCJsController13sendOSCFromJSERKN4juce3var18NativeFunctionArgsE + 640
4   LGML                                0x00124da5 _ZNSt3__110__function6__funcIPFN4juce3varERKNS3_18NativeFunctionArgsEENS_9allocatorIS8_EES7_EclES6_ + 21
5   LGML                                0x003f138d _ZNK4juce16JavascriptEngine10RootObject12FunctionCall14invokeFunctionERKNS1_5ScopeERKNS_3varES8_ + 1357
6   LGML                                0x003f2306 _ZNK4juce16JavascriptEngine10RootObject12FunctionCall9getResultERKNS1_5ScopeE + 1686
7   LGML                                0x003ea7c9 _ZNK4juce16JavascriptEngine10RootObject10Expression7performERKNS1_5ScopeEPNS_3varE + 25
8   LGML                                0x003f455f _ZNK4juce16JavascriptEngine10RootObject14BlockStatement7performERKNS1_5ScopeEPNS_3varE + 47
9   LGML                                0x003f195f _ZNK4juce16JavascriptEngine10RootObject14FunctionObject6invokeERKNS1_5ScopeERKNS_3var18NativeFunctionArgsE + 543
10  LGML                                0x003f8f21 _ZNK4juce16JavascriptEngine10RootObject5Scope19findAndInvokeMethodERKNS_10IdentifierERKNS_3var18NativeFunctionArgsERS6_ + 257
11  LGML                                0x003f8ca4 _ZN4juce16JavascriptEngine12callFunctionERKNS_10IdentifierERKNS_3var18NativeFunctionArgsEPNS_6ResultE + 340
12  LGML                                0x002261b4 _ZN13JsEnvironment26callFunctionFromIdentifierERKN4juce10IdentifierERKNS0_3var18NativeFunctionArgsEbPNS0_6ResultE + 356
13  LGML                                0x00226ac3 _ZN13JsEnvironment12callFunctionERKN4juce6StringERKNS0_3varEbPNS0_6ResultE + 163
14  LGML                                0x00224341 _ZN13JsEnvironment21parameterValueChangedEP13ParameterBasePNS0_8ListenerE + 257
15  LGML                                0x00224ed8 _ZThn20_N13JsEnvironment21parameterValueChangedEP13ParameterBasePNS0_8ListenerE + 24
16  LGML                                0x00164fca _ZN4juce12ListenerListIN13ParameterBase8ListenerENS_5ArrayIPS2_NS_20DummyCriticalSectionELi0EEEE4callIJPS1_S4_EJS9_RS4_EEEvMS2_FvDpT_EDpOT0_ + 346
17  LGML                                0x00163b06 _ZN13ParameterBase13tryToSetValueERKN4juce3varEbbPNS_8ListenerE + 310
18  LGML                                0x00133146 _ZN15UndoableHelpers22UndoableSetValueAction7performEv + 262
19  LGML                                0x0040bd63 _ZN4juce11UndoManager7performEPNS_14UndoableActionE + 67
20  LGML                                0x0013293d _ZN15UndoableHelpers16setValueUndoableEP13ParameterBaseRKN4juce3varEbb + 205
21  LGML                                0x0014aa2e _ZN8SliderUIIdE23setParamNormalizedValueEf + 254
22  LGML                                0x001489ad _ZN8SliderUIIdE9mouseDragERKN4juce10MouseEventE + 573
23  LGML                                0x00490d38 _ZN4juce24MouseInputSourceInternal12setScreenPosENS_5PointIfEENS_4TimeEb + 1016
24  LGML                                0x005196ab _ZN4juce13ComponentPeer16handleMouseEventENS_16MouseInputSource15InputSourceTypeENS_5PointIfEENS_12ModifierKeysEffxNS_10PenDetailsEi + 411
25  LGML                                0x005193d6 _ZN4juce19NSViewComponentPeer14sendMouseEventEP7NSEvent + 486
26  LGML                                0x0051289d _ZN4juce15JuceNSViewClass12mouseDraggedEP11objc_objectP13objc_selectorP7NSEvent + 125
27  AppKit                              0x92800266 -[NSWindow _handleMouseDraggedEvent:] + 35
28  AppKit                              0x928614bb -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 5876
29  AppKit                              0x9285fa49 -[NSWindow(NSEventRouting) sendEvent:] + 547
30  AppKit                              0x926ea476 -[NSApplication(NSEvent) sendEvent:] + 2854
31  AppKit                              0x91f7ad01 -[NSApplication run] + 1018
32  LGML                                0x002b0682 main + 418
33  libdyld.dylib                       0xa1539395 start + 1

**Comment by Ezrabox** [comment]
Crash au clic sur le volume master de certains mixers

**Comment by Ezrabox** [comment]
[test(14).lgml.zip](https://github.com/OrganicOrchestra/LGML/files/2872490/test.14.lgml.zip)

**Comment by MartinHN** [comment]
ça semble provenir d'un script, peux tu m'envoyer la session complete?

**Comment by MartinHN** [comment]
je bouge l'issue dans #18
