### ISSUE TITLE
1.3.4 Crash en cliquant sur enable des vst "prefx"

### ISSUE THREAD

**Issue by Ezrabox** [OrganicOrchestra/LGML#15]
[test(16).lgml.zip](https://github.com/OrganicOrchestra/LGML/files/2872829/test.16.lgml.zip)

**Comment by Ezrabox** [comment]
0   LGML                                0x00441515 _ZN4juceL11handleCrashEi + 69
1   libsystem_platform.dylib            0xa1742e5b _sigtramp + 43
2   ???                                 0xffffffff 0x0 + 4294967295
3   LGML                                0x001d4650 _ZN15OSCJsController13sendOSCFromJSERKN4juce3var18NativeFunctionArgsE + 640
4   LGML                                0x00167da5 _ZNSt3__110__function6__funcIPFN4juce3varERKNS3_18NativeFunctionArgsEENS_9allocatorIS8_EES7_EclES6_ + 21
5   LGML                                0x0043438d _ZNK4juce16JavascriptEngine10RootObject12FunctionCall14invokeFunctionERKNS1_5ScopeERKNS_3varES8_ + 1357
6   LGML                                0x00435306 _ZNK4juce16JavascriptEngine10RootObject12FunctionCall9getResultERKNS1_5ScopeE + 1686
7   LGML                                0x0042d7c9 _ZNK4juce16JavascriptEngine10RootObject10Expression7performERKNS1_5ScopeEPNS_3varE + 25
8   LGML                                0x0043755f _ZNK4juce16JavascriptEngine10RootObject14BlockStatement7performERKNS1_5ScopeEPNS_3varE + 47
9   LGML                                0x0043495f _ZNK4juce16JavascriptEngine10RootObject14FunctionObject6invokeERKNS1_5ScopeERKNS_3var18NativeFunctionArgsE + 543
10  LGML                                0x0043bf21 _ZNK4juce16JavascriptEngine10RootObject5Scope19findAndInvokeMethodERKNS_10IdentifierERKNS_3var18NativeFunctionArgsERS6_ + 257
11  LGML                                0x0043bca4 _ZN4juce16JavascriptEngine12callFunctionERKNS_10IdentifierERKNS_3var18NativeFunctionArgsEPNS_6ResultE + 340
12  LGML                                0x002691b4 _ZN13JsEnvironment26callFunctionFromIdentifierERKN4juce10IdentifierERKNS0_3var18NativeFunctionArgsEbPNS0_6ResultE + 356
13  LGML                                0x00269ac3 _ZN13JsEnvironment12callFunctionERKN4juce6StringERKNS0_3varEbPNS0_6ResultE + 163
14  LGML                                0x00267341 _ZN13JsEnvironment21parameterValueChangedEP13ParameterBasePNS0_8ListenerE + 257
15  LGML                                0x00267ed8 _ZThn20_N13JsEnvironment21parameterValueChangedEP13ParameterBasePNS0_8ListenerE + 24
16  LGML                                0x001a7fca _ZN4juce12ListenerListIN13ParameterBase8ListenerENS_5ArrayIPS2_NS_20DummyCriticalSectionELi0EEEE4callIJPS1_S4_EJS9_RS4_EEEvMS2_FvDpT_EDpOT0_ + 346
17  LGML                                0x001a6b06 _ZN13ParameterBase13tryToSetValueERKN4juce3varEbbPNS_8ListenerE + 310
18  LGML                                0x00176146 _ZN15UndoableHelpers22UndoableSetValueAction7performEv + 262
19  LGML                                0x0044ed63 _ZN4juce11UndoManager7performEPNS_14UndoableActionE + 67
20  LGML                                0x0017593d _ZN15UndoableHelpers16setValueUndoableEP13ParameterBaseRKN4juce3varEbb + 205
21  LGML                                0x00183500 _ZN12BoolToggleUI9mouseDownERKN4juce10MouseEventE + 112
22  LGML                                0x0055208c _ZN4juce24MouseInputSourceInternal10setButtonsENS_5PointIfEENS_4TimeENS_12ModifierKeysE + 2684
23  LGML                                0x0055c7ac _ZN4juce13ComponentPeer16handleMouseEventENS_16MouseInputSource15InputSourceTypeENS_5PointIfEENS_12ModifierKeysEffxNS_10PenDetailsEi + 668
24  LGML                                0x0055c3d6 _ZN4juce19NSViewComponentPeer14sendMouseEventEP7NSEvent + 486
25  LGML                                0x005555f5 _ZN4juce15JuceNSViewClass9mouseDownEP11objc_objectP13objc_selectorP7NSEvent + 245
26  AppKit                              0x928639ff -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5864
27  AppKit                              0x928614bb -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 5876
28  AppKit                              0x9285fa49 -[NSWindow(NSEventRouting) sendEvent:] + 547
29  AppKit                              0x926ea476 -[NSApplication(NSEvent) sendEvent:] + 2854
30  AppKit                              0x91f7ad01 -[NSApplication run] + 1018
31  LGML                                0x002f3682 main + 418
32  libdyld.dylib                       0xa1539395 start + 1

**Comment by Ezrabox** [comment]
est-ce aussi du à un script?

**Comment by MartinHN** [comment]
oui
