### ISSUE TITLE
1.3.4 crash en cliquant sur le looper  (test#17)

### ISSUE THREAD

**Issue by Ezrabox** [OrganicOrchestra/LGML#17]
0   LGML                                0x003bd515 _ZN4juceL11handleCrashEi + 69
1   libsystem_platform.dylib            0xa1742e5b _sigtramp + 43
2   ???                                 0xffffffff 0x0 + 4294967295
3   LGML                                0x00150650 _ZN15OSCJsController13sendOSCFromJSERKN4juce3var18NativeFunctionArgsE + 640
4   LGML                                0x000e3da5 _ZNSt3__110__function6__funcIPFN4juce3varERKNS3_18NativeFunctionArgsEENS_9allocatorIS8_EES7_EclES6_ + 21
5   LGML                                0x003b038d _ZNK4juce16JavascriptEngine10RootObject12FunctionCall14invokeFunctionERKNS1_5ScopeERKNS_3varES8_ + 1357
6   LGML                                0x003b1306 _ZNK4juce16JavascriptEngine10RootObject12FunctionCall9getResultERKNS1_5ScopeE + 1686
7   LGML                                0x003a97c9 _ZNK4juce16JavascriptEngine10RootObject10Expression7performERKNS1_5ScopeEPNS_3varE + 25
8   LGML                                0x003b355f _ZNK4juce16JavascriptEngine10RootObject14BlockStatement7performERKNS1_5ScopeEPNS_3varE + 47
9   LGML                                0x003b095f _ZNK4juce16JavascriptEngine10RootObject14FunctionObject6invokeERKNS1_5ScopeERKNS_3var18NativeFunctionArgsE + 543
10  LGML                                0x003b7f21 _ZNK4juce16JavascriptEngine10RootObject5Scope19findAndInvokeMethodERKNS_10IdentifierERKNS_3var18NativeFunctionArgsERS6_ + 257
11  LGML                                0x003b7ca4 _ZN4juce16JavascriptEngine12callFunctionERKNS_10IdentifierERKNS_3var18NativeFunctionArgsEPNS_6ResultE + 340
12  LGML                                0x001e51b4 _ZN13JsEnvironment26callFunctionFromIdentifierERKN4juce10IdentifierERKNS0_3var18NativeFunctionArgsEbPNS0_6ResultE + 356
13  LGML                                0x001e5ac3 _ZN13JsEnvironment12callFunctionERKN4juce6StringERKNS0_3varEbPNS0_6ResultE + 163
14  LGML                                0x001e3341 _ZN13JsEnvironment21parameterValueChangedEP13ParameterBasePNS0_8ListenerE + 257
15  LGML                                0x001e3ed8 _ZThn20_N13JsEnvironment21parameterValueChangedEP13ParameterBasePNS0_8ListenerE + 24
16  LGML                                0x00123fca _ZN4juce12ListenerListIN13ParameterBase8ListenerENS_5ArrayIPS2_NS_20DummyCriticalSectionELi0EEEE4callIJPS1_S4_EJS9_RS4_EEEvMS2_FvDpT_EDpOT0_ + 346
17  LGML                                0x00122b06 _ZN13ParameterBase13tryToSetValueERKN4juce3varEbbPNS_8ListenerE + 310
18  LGML                                0x001a6800 _ZN11LooperTrack29updatePendingLooperTrackStateEi + 1376
19  LGML                                0x001938d7 _ZN10LooperNode20processBlockInternalERN4juce11AudioBufferIfEERNS0_10MidiBufferE + 2119
20  LGML                                0x001d6919 _ZN8NodeBase12processBlockERN4juce11AudioBufferIfEERNS0_10MidiBufferE + 1145
21  LGML                                0x001d6d9d _ZThn348_N8NodeBase12processBlockERN4juce11AudioBufferIfEERNS0_10MidiBufferE + 29
22  LGML                                0x0030c4ec _ZN4juce19GraphRenderSequenceIfE9ProcessOp7performERKNS1_7ContextE + 748
23  LGML                                0x0030d4c4 _ZN4juce19GraphRenderSequenceIfE7performERNS_11AudioBufferIfEERNS_10MidiBufferEPNS_13AudioPlayHeadE + 724
24  LGML                                0x00300c42 _ZN4juce19AudioProcessorGraph12processBlockERNS_11AudioBufferIfEERNS_10MidiBufferE + 226
25  LGML                                0x003619a9 _ZN4juce20AudioProcessorPlayer21audioDeviceIOCallbackEPPKfiPPfii + 1385
26  LGML                                0x00285c56 _ZN4juce18AudioDeviceManager15CallbackHandler21audioDeviceIOCallbackEPPKfiPPfii + 1366
27  LGML                                0x00282ee7 _ZN4juce16CoreAudioClasses17CoreAudioInternal11audioIOProcEmPK14AudioTimeStampPK15AudioBufferListS4_PS5_S4_Pv + 423
28  CoreAudio                           0x93e5af16 _ZN19HALC_ProxyIOContext10IOWorkLoopEv + 7936
29  CoreAudio                           0x93e58dc4 _ZN19HALC_ProxyIOContext13IOThreadEntryEPv + 236
30  CoreAudio                           0x93e89813 ___ZN19HALC_ProxyIOContextC2Emj_block_invoke + 20
31  CoreAudio                           0x93e58c97 _ZN13HALB_IOThread5EntryEPv + 71
32  libsystem_pthread.dylib             0xa174c047 _pthread_body + 184
33  libsystem_pthread.dylib             0xa174bf8f _pthread_body + 0
34  libsystem_pthread.dylib             0xa174b84a thread_start + 34

**Comment by MartinHN** [comment]
provient d'un script , peux tu m'envoyer la session complete?

**Comment by MartinHN** [comment]
je bouge l'issue dans #18
