### ISSUE TITLE
scripts crash in 1.3.4

### ISSUE THREAD

**Issue by MartinHN** [OrganicOrchestra/LGML#18]
regroupe les issues de crash de scripts

**Comment by Ezrabox** [comment]
[1.3.4_test(17).lgml.zip](https://github.com/OrganicOrchestra/LGML/files/2872913/1.3.4_test.17.lgml.zip)
[Scripts.zip](https://github.com/OrganicOrchestra/LGML/files/2872914/Scripts.zip)

**Comment by Ezrabox** [comment]
pour les scripts qui ne sont plus compatibles et font crasher la nouvelle version, est ce qu'il faut rééditer les scriptes ou alors c'est côté lgml que la compatibilité va se faire?
