### ISSUE TITLE
Download button is missing

### ISSUE THREAD

**Issue by AlexFundorin** [OrganicOrchestra/LGML#6]
No button for any system, especially win x64. Tried Firefox and Chrome.
https://i.imgur.com/08GJWyA.png

**Comment by MartinHN** [comment]
binaries deployement strategy is still in progress, should be soon enough though,
any one can send a PM if interested by helping out with beta testing

**Comment by AlexFundorin** [comment]
If LGML can act as midi<>osc bridge (with some extra logic) and supports sysex command, I can help you with testing.

**Comment by MartinHN** [comment]
too old, dropping (see releases)
