### ISSUE TITLE
1.3.3 ne peut pas créer plusieur node .js

### ISSUE THREAD

**Issue by Ezrabox** [OrganicOrchestra/LGML#8]
si je créé un deuxième node .js, le précédent disparait

**Comment by MartinHN** [comment]
Je n'arrive pas à reproduire ce bug as tu plus d'info?

**Comment by Ezrabox** [comment]
hier c'était récurent, aujourd'hui pas de problème, je le ferme jusqu'à ce que ça réapparaisse
